logging:
  level:
    .: error
    org.springframework: ERROR
    com.mkyong: ERROR

spring:
  profiles:
    active: "dev"
  resources:
    static-locations: classpath:/static/

springdoc:
  swagger-ui:
    path: /v3/swagger-ui
    
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/discovery
    username: root
    password: cofomo.123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
swagger:
  basepath: https://localhost:8080
  description: Test server on localhost
      
---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mysql:3306/discovery
    username: root	
    password: cofomo.123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

swagger:
  basepath: https://cofomo.io/discovery/v1/api
  description: Test server for deployment
  


